# Generated by Django 4.2.16 on 2024-11-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_alter_assignment_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
    ]
