# Generated by Django 4.2.16 on 2024-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
