# Generated by Django 4.2.16 on 2024-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_lesson_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
