# Generated by Django 4.2.16 on 2024-12-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
