# Generated by Django 4.2.16 on 2024-12-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_lesson_duration_lesson_hls_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='hls_directory',
        ),
    ]
