# Generated by Django 4.2.16 on 2024-12-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0011_remove_lesson_hls_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
