# Generated by Django 4.2.16 on 2024-12-10 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0014_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Expert_Notification',
        ),
    ]
