# Generated by Django 4.2.16 on 2024-12-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_quizanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
    ]
