# Generated by Django 4.2.16 on 2024-12-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0017_delete_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='expert.quizassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.question')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
