# Generated by Django 4.2.16 on 2024-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0018_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.FloatField(default=35),
        ),
    ]
