# Generated by Django 4.2.16 on 2024-12-12 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0019_quiz_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
