# Generated by Django 4.2.16 on 2024-12-12 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0020_quizassignment_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quizassignment',
            name='completed_date',
            field=models.DateTimeField(),
        ),
    ]
