# Generated by Django 4.2.16 on 2024-12-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0021_quizassignment_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizassignment',
            name='submitted_at',
        ),
    ]
