# Generated by Django 4.2.16 on 2024-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0022_remove_quizassignment_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizassignment',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
