# Generated by Django 4.2.16 on 2024-11-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_number',
        ),
    ]
