# Generated by Django 4.2.16 on 2024-12-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
