# Generated by Django 4.2.16 on 2024-12-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
