# Generated by Django 4.2.16 on 2024-11-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deleted',
            new_name='deleted_for_student',
        ),
    ]
