# Generated by Django 4.2.16 on 2024-11-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_deleted_message_deleted_for_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for_expert',
            field=models.BooleanField(default=False),
        ),
    ]
